---
title: "covariate_regression"
author: "Haozhi Ma"
date: "10/29/2019"
output: html_document
---
now I load the data to this script


```{R}
df.for.clustering<-read.csv('C:\\Users\\haozh\\Desktop\\root_ratio\\grsearch\\forest_rsr_sample_for_grsearch_20191022.csv')

```
have a look at the dataset
```{R}
names(df.for.clustering)

```

delete the irrelevant covariates

```{R}
df.for.clustering_sub<-subset(df.for.clustering, select = -c(system.index, Abs_Lat, Pixel_Lat, Pixel_Long, X, X_1, index, latitude, longitude, latitude_209564535, longitude_209564535, .geo, Global_Biomass_IPCC))

names(df.for.clustering_sub)
```
load the package

```{R}
library(ClustOfVar)
library(cluster)

xquant<-df.for.clustering_sub[,c(1:24,32:59,61,62)]
xquant<-scale(xquant)
```
seek out the patterns in the variables using a dendrogram. Dendrograms are graphic displays that show how closely each of the variables are related.
```{R}

tree<-hclustvar(xquant)
plot(tree)
```
estimate the number of clusters

```{R}
stab<-stability(tree, B = 50)


```

It seems that 35 clusters show the best stability

```{R}
k.means<-kmeansvar(xquant,init = 18)
summary(k.means)

```

```{R}
df<-df.for.clustering[,c(5,7,17,63,4,12,27,62,41,45,37,52,54,57,74,72,68,66)]
namelist<-names(df)
namelist
```


```{R}
#df<-scale(df)
#df<-as.data.frame(df)
summary(df)
```



```{R}
#df<-scale(df)
#library(relaimpo)
for(i in 1:(NCOL(df)-1)){
corr<-lm(scale(log(ratio))~scale(df[,i]), data = df)
print(summary(corr))
print(paste0(namelist[i],'____',corr$coefficients[2]))
}
```

Let's here check sac. Now Moran's I
```{R}
library(spdep)
library(ncf)
```

```{R}
coords<-cbind(df$longitude, df$latitude)
corrds<-as.matrix(coords)

```

define the neighborhood (here distance is 1.5)

```{R}
nb1.5<-dnearneigh(coords,0,2,longlat = FALSE)



```

spatial weights illustrated with coding style 'W'

```{R}
nb1.5.w<-nb2listw(nb1.5, glist = NULL, style = 'W', zero.policy = TRUE)


```
```{R}
library(HH)
#library(car)

cor.matrix<-cor(df[,1:15], use = 'complete.obs', method = 'pearson')
cor.dist<-abs(as.dist(cor.matrix))
cor.cluster<-hclust(1-cor.dist)
plot(cor.cluster)


```

```{R}
vif(df[,c(1:10,12,13,15)])


```




```{R}
ols<-lm(scale(log(ratio))~scale(df$Annual_Precipitation)+scale(df$Bulk_Density_15cm)+scale(df$Human_Footprint_2009)+scale(df$elevation)+scale(df$Annual_Mean_Temperature)+scale(df$Depth_to_Bedrock)+scale(df$NDVI)+scale(df$eastness)+scale(df$Radiation_of_Warmest_Quarter)+scale(df$Sand_Content_15cm)+scale(df$Precipitation_Seasonality)+scale(df$soil_moisture),data = df,na.action = na.pass)
sum_ols<-summary(ols)
sum_ols
res.ols<-residuals(ols)
```
```{R}
write.csv(sum_ols$coefficients,'C:\\Users\\haozh\\Desktop\\root_ratio\\cor_result\\forest_ols.csv')



```
```{R}
cor.ols.res<-correlog(df$longitude, df$latitude, z=res.ols, na.rm=T, increment=1, resamp=1, latlon = FALSE)



```

plot the correlogram

```{R}
plot(cor.ols.res$correlation[1:20], type = 'b', pch = 1, cex = 1.2, lwd = 1.5, xlab = 'distance', ylab = "Moran's I", cex.lab = 1.5, cex.axis = 1.2)
abline(h = 0)
title(main = 'OLS residuals', cex = 1.5)

```
```{R}
moran.test(res.ols, nb1.5.w, zero.policy = TRUE)


```

run the sar models
```{R}
sem.nb1.5.w<-errorsarlm(ols, listw = nb1.5.w,zero.policy = TRUE)
summary(sem.nb1.5.w)



```

```{R}
sum_sem<-summary(sem.nb1.5.w)
sum_sem$Coef

write.csv(sum_sem$Coef, 'C:\\Users\\haozh\\Desktop\\root_ratio\\cor_result\\forest_sem.csv')

```



correlogram

```{R}
cor.sem.nb1.5.w<-correlog(df$longitude, df$latitude, z = residuals(sem.nb1.5.w), na.rm = T, increment = 1, resamp = 1, latlon = FALSE)
plot(cor.sem.nb1.5.w$correlation[1:35], type="b", pch=4, cex=1.2, lwd=1.5, xlab="distance", ylab="Moran's I", cex.lab=1.5, cex.axis=1.2)
abline(h=0)

```

```{R}
plot(cor.ols.res$correlation[1:20], type="b", pch=1, cex=1.5, lwd=1.5, xlab="Distance class", ylab="Moran's I", cex.lab=1.5, cex.axis=1.5)
abline(h=0)

# then SARlag model residuals
points(cor.sem.nb1.5.w$correlation[1:20], pch=2, cex=1.2)
lines(cor.sem.nb1.5.w$correlation[1:20], lwd=1.5)



```

```{R}
moran.test(residuals(sem.nb1.5.w),nb1.5.w, zero.policy = TRUE)

```




grassland

```{R}
grassdf.for.clustering<-read.csv('C:\\Users\\haozh\\Desktop\\root_ratio\\grsearch\\grass_rsr_sample_for_grsearch_20191022.csv')

```
have a look at the dataset
```{R}
names(grassdf.for.clustering)

```



```{R}
df<-grassdf.for.clustering[,c(5,7,17,63,4,12,27,62,41,45,37,52,54,57,74,72,68,66)]
namelist<-names(df)
namelist[1]
```


```{R}
#df<-scale(df)
#df<-as.data.frame(df)
summary(df)
```


```{R}
coords<-cbind(df$longitude, df$latitude)
corrds<-as.matrix(coords)

```

define the neighborhood (here distance is 1.5)

```{R}
nb1.5<-dnearneigh(coords,0,2,longlat = FALSE)



```

spatial weights illustrated with coding style 'W'

```{R}
nb1.5.w<-nb2listw(nb1.5, glist = NULL, style = 'W', zero.policy = TRUE)


```


```{R}
ols<-lm(scale(log(ratio))~scale(df$Annual_Precipitation)+scale(df$Bulk_Density_15cm)+scale(df$Human_Footprint_2009)+scale(df$elevation)+scale(df$Annual_Mean_Temperature)+scale(df$Depth_to_Bedrock)+scale(df$NDVI)+scale(df$eastness)+scale(df$Precipitation_Seasonality)+scale(df$Radiation_of_Warmest_Quarter)+scale(df$Sand_Content_15cm)+scale(df$soil_moisture),data = df)
summary(ols)
res.ols<-residuals(ols)
```
```{R}
grass_sum_ols<-summary(ols)

write.csv(grass_sum_ols$coefficients, 'C:\\Users\\haozh\\Desktop\\root_ratio\\cor_result\\grass_ols.csv')


```

```{R}
cor.ols.res<-correlog(df$longitude, df$latitude, z=residuals(ols), na.rm=T, increment=1, resamp=1,latlon = FALSE)



```

plot the correlogram

```{R}
plot(cor.ols.res$correlation[1:35], type = 'b', pch = 1, cex = 1.2, lwd = 1.5, xlab = 'distance', ylab = "Moran's I", cex.lab = 1.5, cex.axis = 1.2)
abline(h = 0)
title(main = 'OLS residuals', cex = 1.5)

```
```{R}
moran.test(res.ols, nb1.5.w,zero.policy = TRUE)


```

```{R}
sem.nb1.5.w<-errorsarlm(ols, listw = nb1.5.w,zero.policy = TRUE)
summary(sem.nb1.5.w)



```

```{R}

grass_sum_sem<-summary(sem.nb1.5.w)
write.csv(grass_sum_sem$Coef, 'C:\\Users\\haozh\\Desktop\\root_ratio\\cor_result\\grass_sem.csv')

```




```{R}
cor.sem.nb1.5.w<-correlog(df$longitude, df$latitude, z = residuals(sem.nb1.5.w), na.rm = T, increment = 1, resamp = 1, latlon = FALSE)
plot(cor.sem.nb1.5.w$correlation[1:35], type="b", pch=4, cex=1.2, lwd=1.5, xlab="distance", ylab="Moran's I", cex.lab=1.5, cex.axis=1.2)
abline(h=0)

```

```{R}
plot(cor.ols.res$correlation[1:20], type="b", pch=1, cex=1.5, lwd=1.5, xlab="Distance class", ylab="Moran's I", cex.lab=1.5, cex.axis=1.5)
abline(h=0)

# then SARlag model residuals
points(cor.sem.nb1.5.w$correlation[1:20], pch=2, cex=1.2)
lines(cor.sem.nb1.5.w$correlation[1:20], lwd=1.5)


```

```{R}
moran.test(residuals(sem.nb1.5.w), nb1.5.w,zero.policy = TRUE)

```


shrublands


```{R}
shrubdf.for.clustering<-read.csv('C:\\Users\\haozh\\Desktop\\root_ratio\\grsearch\\shrub_rsr_sample_for_grsearch_20191024.csv')

```
have a look at the dataset
```{R}
names(shrubdf.for.clustering)

```



```{R}
df<-shrubdf.for.clustering[,c(5,7,17,63,4,12,27,62,41,45,37,52,54,57,74,72,68,66)]
namelist<-names(df)
namelist[1]
```


```{R}
#df<-scale(df)
#df<-as.data.frame(df)
summary(df)
```


```{R}
coords<-cbind(df$longitude, df$latitude)
corrds<-as.matrix(coords)

```

define the neighborhood (here distance is 2)

```{R}
nb1.5<-dnearneigh(coords,0,2,longlat = FALSE)



```

spatial weights illustrated with coding style 'W'

```{R}
nb1.5.w<-nb2listw(nb1.5, glist = NULL, style = 'W', zero.policy = TRUE)


```


```{R}
ols<-lm(scale(log(ratio))~scale(df$Annual_Precipitation)+scale(df$Bulk_Density_15cm)+scale(df$Human_Footprint_2009)+scale(df$elevation)+scale(df$Annual_Mean_Temperature)+scale(df$Depth_to_Bedrock)+scale(df$NDVI)+scale(df$eastness)+scale(df$Precipitation_Seasonality)+scale(df$Radiation_of_Warmest_Quarter)+scale(df$Sand_Content_15cm)+scale(df$soil_moisture),data = df)
summary(ols)
res.ols<-residuals(ols)
```
```{R}

shrub_sum_ols<-summary(ols)
write.csv(shrub_sum_ols$coefficients, 'C:\\Users\\haozh\\Desktop\\root_ratio\\cor_result\\shrub_ols.csv')

```

```{R}
cor.ols.res<-correlog(df$longitude, df$latitude, z=residuals(ols), na.rm=T, increment=1, resamp=1,latlon = FALSE)



```

plot the correlogram

```{R}
plot(cor.ols.res$correlation[1:35], type = 'b', pch = 1, cex = 1.2, lwd = 1.5, xlab = 'distance', ylab = "Moran's I", cex.lab = 1.5, cex.axis = 1.2)
abline(h = 0)
title(main = 'OLS residuals', cex = 1.5)

```


```{R}
moran.test(res.ols, nb1.5.w,zero.policy = TRUE)


```

```{R}
sem.nb1.5.w<-errorsarlm(ols, listw = nb1.5.w,zero.policy = TRUE)
summary(sem.nb1.5.w)


```

```{R}
shrub_sum_sem<-summary(sem.nb1.5.w)

write.csv(shrub_sum_sem$Coef, 'C:\\Users\\haozh\\Desktop\\root_ratio\\cor_result\\shrub_sem.csv')

```



```{R}
cor.sem.nb1.5.w<-correlog(df$longitude, df$latitude, z = residuals(sem.nb1.5.w), na.rm = T, increment = 1, resamp = 1, latlon = FALSE)
plot(cor.sem.nb1.5.w$correlation[1:35], type="b", pch=4, cex=1.2, lwd=1.5, xlab="distance", ylab="Moran's I", cex.lab=1.5, cex.axis=1.2)
abline(h=0)

```

```{R}
plot(cor.ols.res$correlation[1:20], type="b", pch=1, cex=1.5, lwd=1.5, xlab="Distance class", ylab="Moran's I", cex.lab=1.5, cex.axis=1.5)
abline(h=0)

# then SARlag model residuals
points(cor.sem.nb1.5.w$correlation[1:20], pch=2, cex=1.2)
lines(cor.sem.nb1.5.w$correlation[1:20], lwd=1.5)


```

```{R}
moran.test(residuals(sem.nb1.5.w), nb1.5.w,zero.policy = TRUE)

```


```{R}
forest.sem<-read.csv('C:\\Users\\haozh\\Desktop\\root_ratio\\cor_result\\forest_sem.csv')
forest.sem
```

```{R}
forest.sem$vegetation.type<-'forest'
names(forest.sem)
```
```{R}
grass.sem<-read.csv('C:\\Users\\haozh\\Desktop\\root_ratio\\cor_result\\grass_sem.csv')
grass.sem$vegetation.type<-'grassland'
grass.sem

```
```{R}
shrub.sem<-read.csv('C:\\Users\\haozh\\Desktop\\root_ratio\\cor_result\\shrub_sem.csv')
shrub.sem$vegetation.type<-'shrubland'
shrub.sem

```
```{R}
rsrplot<-rbind(forest.sem, grass.sem)
rsrplot<-rbind(rsrplot,shrub.sem)

```

```{R}
rsrplot
```

```{R}
rsrplot$X<-factor(rsrplot$X, levels = c('Human Footprint','Elevation','Eastness','Soil Moisture','Sand Content (0 to 15cm)','Depth to Bedrock','Bulk Density (0 to 15cm)','NDVI','Radiation of Warmest Quarter','Precipitation Seasonality','Annual Precipitation','Annual Mean Temperature'), ordered = TRUE)
rsrplot$X
```
```{R}
rsrplot

```



```{R}
library(ggplot2)

ggplot(rsrplot, aes(x = X, y = Estimate, fill = vegetation.type))+
  geom_bar(stat = 'identity',position = position_dodge(),color = 'black')+
  #geom_errorbar(aes(ymin = Estimate - 2*rsrplot$Std..Error, ymax = Estimate + 2*rsrplot$Std..Error), position = position_dodge(.9), width = 0)+
  coord_flip()+
  theme_classic()+
  geom_hline(yintercept = 0)+
  theme(axis.text = element_text(angle = 0, hjust = 1))+
  annotate('rect',xmin = -Inf, xmax = 1.5, ymin = -Inf, ymax = Inf, fill = 'grey80',alpha = 0.3)+
  annotate('rect',xmin = 2.5, xmax = 3.5, ymin = -Inf, ymax = Inf, fill = 'grey80', alpha = 0.3)+
  annotate('rect',xmin = 4.5, xmax = 5.5, ymin = -Inf, ymax = Inf, fill = 'grey80', alpha = 0.3)+
  annotate('rect',xmin = 6.5, xmax = 7.5, ymin = -Inf, ymax = Inf, fill = 'grey80', alpha = 0.3)+
  annotate('rect',xmin = 8.5, xmax = 9.5, ymin = -Inf, ymax = Inf, fill = 'grey80', alpha = 0.3)+
  annotate('rect',xmin = 10.5, xmax = 11.5, ymin = -Inf, ymax = Inf, fill = 'grey80', alpha = 0.3)+
  annotate('text', x = 11.64, y = -0.21,label = '*')+
  annotate('text', x = 10.24, y = 0.31, label  = '*')+
  #annotate('text', x = 9.24, y = -0.18, label = '*')+
  annotate('text', x = 8.64, y = 0.09, label = '*')+
  annotate('text', x = 7.94, y = -0.13, label = '*')+
  annotate('text',x = 6.64, y = -0.09, label = '*')+
  annotate('text', x = 5.94, y = 0.08, label = '*')+
  annotate('text', x = 4.64, y = 0.1, label = '*')+
  #annotate('text', x = 3.94, y = -0.13, label = '*')+
  annotate('text',x = 3.64, y = -0.16, label = '*')+
  annotate('text',x = 1.94, y = 0.29, label = '*')+
  annotate('text',x = 1.64, y = -0.17, label = '*')
 
  

```



