---
title: "h2o_grsearch_rsr"
author: "Haozhi Ma"
date: "10/19/2019"
output: html_document
---
```{R}
install.packages('h2o')
install.packages('tictoc')
install.packages('foreach')
install.packages('doParallel')

```


```{R}
library(data.table)
library(h2o)
library(raster)
library(tictoc)
library(foreach)
library(doParallel)
library(tidyverse)
```


### Load sample dataset
We only need to run one of the three datasets according to which vegetation type that we would like to explore.
```{R}
forest.rsr.grsearch<-read.csv('C:\\Users\\haozh\\Desktop\\root_ratio\\grsearch\\forest_rsr_sample_for_grsearch_20191022.csv')

```
```{R}
grass.rsr.grsearch<-read.csv('C:\\Users\\haozh\\Desktop\\root_ratio\\grsearch\\grass_rsr_sample_for_grsearch_20191022.csv')

```

```{R}
shrub.rsr.grsearch<-read.csv('C:\\Users\\haozh\\Desktop\\root_ratio\\grsearch\\shrub_rsr_sample_for_grsearch_20191024.csv')

```
#### see the column names of the sample

```{R}
names(forest.rsr.grsearch)
median(forest.rsr.grsearch$ratio)
mad(forest.rsr.grsearch$ratio)
mean(forest.rsr.grsearch$ratio)
```
```{R}
names(grass.rsr.grsearch)
median(grass.rsr.grsearch$ratio)
mad(grass.rsr.grsearch$ratio)
mean(grass.rsr.grsearch$ratio)
```


```{R}
names(shrub.rsr.grsearch)
median(shrub.rsr.grsearch$ratio)
mad(shrub.rsr.grsearch$ratio)
mean(shrub.rsr.grsearch$ratio)
```


#### deselect the covariates that we do not want

Below three chunks, choose one according to the vegetation type you work on. DO NOT RUN THEM ALL AT THE SAME TIME!

```{R}
#bandnames<-names(forest.rsr.grsearch)
bands<-subset(forest.rsr.grsearch, select = -c(Abs_Lat, system.index,latitude,longitude,index,Pixel_Lat, Pixel_Long,latitude_209564535,longitude_209564535,ratio,.geo,Global_Biomass_IPCC,X,X_1))
bandnames<-names(bands)
print(bandnames)
```

```{R}
bands<-subset(grass.rsr.grsearch, select = -c(system.index,latitude,longitude,index,Pixel_Lat, Pixel_Long,latitude_209564535,longitude_209564535,ratio,.geo,Global_Biomass_IPCC,X,X_1,Abs_Lat))
bandnames<-names(bands)
print(bandnames)

```

```{R}
bands<-subset(shrub.rsr.grsearch, select = -c(system.index,latitude,longitude,index,Pixel_Lat, Pixel_Long,latitude_209564535,longitude_209564535,ratio,.geo,Global_Biomass_IPCC,X,X_1,Abs_Lat))
bandnames<-names(bands)
print(bandnames)

```

#### load the data
Same as before, run one of the three each time :-)

```{R}
rawmatrix<-forest.rsr.grsearch


```
```{R}
rawmatrix<-grass.rsr.grsearch

```

```{R}

rawmatrix<-shrub.rsr.grsearch
```

```{R}
rawmatrix<-rawmatrix[!(is.na(rawmatrix$latitude)),]

```


#### set the name of the dependent variable

```{R}
vartomodel<-'ratio'
```
#### select the bands from the regression matrix
```{R}
regressionmatrix<-rawmatrix %>%
  select(bandnames, vartomodel)
```

#### Initiate the H2o cluster

This chunk need to be careful, you'd better understand more by checking ?h2o.init.
```{R}
localH2O<-h2o.init(nthreads = 7, max_mem_size = '500g', ignore_config = TRUE)

```


#### import the regression matrix
```{R}
regmatrixh2o<-as.h2o(regressionmatrix, destination_frame = 'regMatrixH2O')
```

#### simple rf model, no grsearch

```{R}
rf.model.rsr<-h2o.randomForest(
  y = vartomodel,
  training_frame = regmatrixh2o,
  ntrees = 100,
  mtries = 4,
  min_rows = 4,
  sample_rate = 0.632,
  nfolds = 10,
  fold_assignment = 'Modulo',
  keep_cross_validation_predictions = TRUE,
  seed = 0
)

h2o.varimp_plot(rf.model.rsr)

h2o.r2(rf.model.rsr, xval = TRUE)
```
#### let's try to save the model. This will save time next time

```{R}
h2o.saveModel(object = rf.model.rsr, path = 'C:\\Users\\haozh\\Desktop\\root_ratio\\grsearch\\best_grass_models',force = TRUE)

```
#### load the saved model


```{R}
saved_model<-h2o.loadModel("C:\\Users\\haozh\\Desktop\\root_ratio\\grsearch\\rf_model_rsr\\DRF_model_R_1571648915981_1")

```

WOW~!


####  set grsearch parameters

```{R}
rf.params<-list(ntrees = c(50,100,150),
                mtries = c(2:10),
                min_rows = c(2:5)
                )

```

#### set grsearch criteria

```{R}
search.criteria<-list(strategy = 'RandomDiscrete', max_models = 150, seed = 0, max_runtime_secs = 3600)


```

#### perform rf grsearch across parameters

```{R}
rf.grid<-h2o.grid('randomForest',
                  y = vartomodel,
                  grid_id = 'rf.grid',
                  training_frame = regmatrixh2o,
                  seed = 0,
                  hyper_params = rf.params,
                  sample_rate = 0.632,
                  nfolds = 10,
                  search_criteria = search.criteria)
```

#### retrieve grid searched model performance sort by R2


```{R}

gc(reset = TRUE)
```


```{R}
rf.grid.perf<-h2o.getGrid(grid_id = 'rf.grid',
                          sort_by = 'R2',
                          decreasing = TRUE)

```

#### show the best models

```{R}

rf.grid.perf<-h2o.getGrid(grid_id = 'rf.grid')

```

```{R}
print(rf.grid.perf@summary_table)

```

#### save the hyperparameters
run one of the three each time.

```{R}
write.csv(rf.grid.perf@summary_table,'C:\\Users\\haozh\\Desktop\\root_ratio\\grsearch\\forest_rfgrsearch_r2_20191022.csv')
```

```{R}
write.csv(rf.grid.perf@summary_table,'C:\\Users\\haozh\\Desktop\\root_ratio\\grsearch\\grass_rfgrsearch_r2_20191022.csv')
```

```{R}
write.csv(rf.grid.perf@summary_table,'C:\\Users\\haozh\\Desktop\\root_ratio\\grsearch\\shrub_rfgrsearch_r2_20191025.csv')

```




#### doing plots


```{R}
fullprediction<-as.data.frame(h2o.predict(bestrf,regmatrixh2o))

trainandpredicted<-as.data.frame(fullprediction)

trainandpredicted$train<-regressionmatrix[[vartomodel]]

```

#### define palette

```{R}
paletteForUse <- c('#d10000', '#ff6622', '#ffda21', '#33dd00', '#1133cc', '#220066', '#330044')
colors <-  colorRampPalette(paletteForUse)(256)

trainandpredicted$dens <- col2rgb(densCols(trainandpredicted$train, trainandpredicted$predict))[1,] + 1L
trainandpredicted$colors = colors[trainandpredicted$dens]

summary(lm(predict ~ train, data = trainandpredicted))

```

#### Plot the predicted vs. ovserved values

```{R}
ggplot(trainandpredicted, 
                      aes(x = predict, 
                          y = train)) +
  geom_point(color = trainandpredicted$colors) +
  labs(x = "Predicted",
       y = "Observed") +
  coord_cartesian(xlim = c(0,6), ylim = c(0,6)) +
  stat_smooth(se = T,
              colour = "black",
              size = 0.5,
              method = "lm") +
  geom_abline(slope = 1,
              intercept = 0,
              na.rm = FALSE, 
              show.legend = NA, 
              linetype = "dashed") +
  theme_bw()

```




