---
title: "shrub_lmer"
author: "Haozhi Ma"
date: "6/8/2020"
output: html_document
---


### This script is used for lmer analysis for shrubland rmfs. This approach is similar to what we did in 'alldata' subsampling analysis. The only difference happens in the random effect.

### The results from this script can be seen in Exteneded Data Fig.3, shrubland panel.

Load the data

```{R}
shrubds<-read.csv('C:\\Users\\haozh\\Desktop\\root_ratio\\grsearch\\shrub_rsr_sample_for_grsearch_20200517.csv') # Read the data
shrubds$veg.type<-'shrub'

names(shrubds)
```

Choose the variables.

```{R}
var.to.choose<-c('Aridity_Index', # This one comprimises the deletion of all precipitation related variables, to make the chosen variables comprehensive.
                 #'elevation',
                 'Annual_Mean_Temperature',
                 #'Temperature_Seasonality',
                 #'Annual_Precipitation',
                 #'Precipitation_Seasonality',
                 'soil_moisture',
                 'cnratio',
                 'Depth_to_Bedrock',
                 'Sand_Content_15cm',
                 'NDVI',
                 'Tree_Density',
                 'rmf')


```

Subset the dataset
```{R}
shrubds.common.ols<-shrubds[,var.to.choose] # Sub-sample the raw data to reduce the satistical burden.
head(shrubds.common.ols)

```

Check the vif
```{R}
library(HH)
vif(shrubds.common.ols[,c(1:8)]) # Check the variable inflation factor. Here we set the threshold is 3.

```
RMF~Annual mean temperature
Also check the SAC from residuals of the regression model.

```{R}
rmfls<-lm(scale(rmf)~scale(Tree_Density)+scale(NDVI)+scale(cnratio)+scale(Aridity_Index)+scale(soil_moisture)+scale(Sand_Content_15cm)+scale(Depth_to_Bedrock),data = shrubds) # Linear model is set.
varls<-lm(scale(Annual_Mean_Temperature)~scale(Tree_Density)+scale(NDVI)+scale(cnratio)+scale(Aridity_Index)+scale(soil_moisture)+scale(Sand_Content_15cm)+scale(Depth_to_Bedrock),data = shrubds)
  common.ols<-lm(resid(rmfls)~resid(varls))
  summary(common.ols)
  
  coords<-cbind(shrubds$longitude, shrubds$latitude) # Set coordinates.
  corrds<-as.matrix(coords)
  nb1.5<-dnearneigh(coords,0,4,longlat = TRUE) # Set distance class.
  nb1.5.w<-nb2listw(nb1.5, glist = NULL, style = 'W', zero.policy = TRUE)
  moran.result<-moran.test(resid(common.ols), nb1.5.w, zero.policy = TRUE)
  moran.result
```
RMF~Tree density
Also check the SAC from residuals of the regression model.

```{R}
rmfls<-lm(scale(rmf)~scale(Annual_Mean_Temperature)+scale(NDVI)+scale(cnratio)+scale(Aridity_Index)+scale(soil_moisture)+scale(Sand_Content_15cm)+scale(Depth_to_Bedrock),data = shrubds) # Linear model is set.
varls<-lm(scale(Tree_Density)~scale(Annual_Mean_Temperature)+scale(NDVI)+scale(cnratio)+scale(Aridity_Index)+scale(soil_moisture)+scale(Sand_Content_15cm)+scale(Depth_to_Bedrock),data = shrubds)
  common.ols<-lm(resid(rmfls)~resid(varls))
  summary(common.ols)
  
  coords<-cbind(shrubds$longitude, shrubds$latitude) # Set coordinates.
  corrds<-as.matrix(coords)
  nb1.5<-dnearneigh(coords,0,4,longlat = TRUE) # Set distance class.
  nb1.5.w<-nb2listw(nb1.5, glist = NULL, style = 'W', zero.policy = TRUE)
  moran.result<-moran.test(resid(common.ols), nb1.5.w, zero.policy = TRUE)
  moran.result
```

RMF~NDVI
Also check the SAC from residuals of the regression model.

```{R}
rmfls<-lm(scale(rmf)~scale(Annual_Mean_Temperature)+scale(Tree_Density)+scale(cnratio)+scale(Aridity_Index)+scale(soil_moisture)+scale(Sand_Content_15cm)+scale(Depth_to_Bedrock),data = shrubds) # Linear model is set.
varls<-lm(scale(NDVI)~scale(Annual_Mean_Temperature)+scale(Tree_Density)+scale(cnratio)+scale(Aridity_Index)+scale(soil_moisture)+scale(Sand_Content_15cm)+scale(Depth_to_Bedrock),data = shrubds)
  common.ols<-lm(resid(rmfls)~resid(varls))
  summary(common.ols)
  
  coords<-cbind(shrubds$longitude, shrubds$latitude) # Set coordinates.
  corrds<-as.matrix(coords)
  nb1.5<-dnearneigh(coords,0,4,longlat = TRUE) # Set distance class.
  nb1.5.w<-nb2listw(nb1.5, glist = NULL, style = 'W', zero.policy = TRUE)
  moran.result<-moran.test(resid(common.ols), nb1.5.w, zero.policy = TRUE)
  moran.result
```
RMF~Soil C:N ratio
Also check the SAC from residuals of the regression model.

```{R}
rmfls<-lm(scale(rmf)~scale(Annual_Mean_Temperature)+scale(Tree_Density)+scale(NDVI)+scale(Aridity_Index)+scale(soil_moisture)+scale(Sand_Content_15cm)+scale(Depth_to_Bedrock),data = shrubds) # Linear model is set.
varls<-lm(scale(cnratio)~scale(Annual_Mean_Temperature)+scale(Tree_Density)+scale(NDVI)+scale(Aridity_Index)+scale(soil_moisture)+scale(Sand_Content_15cm)+scale(Depth_to_Bedrock),data = shrubds)
  common.ols<-lm(resid(rmfls)~resid(varls))
  summary(common.ols)
  
  coords<-cbind(shrubds$longitude, shrubds$latitude) # Set coordinates.
  corrds<-as.matrix(coords)
  nb1.5<-dnearneigh(coords,0,4,longlat = TRUE) # Set distance class.
  nb1.5.w<-nb2listw(nb1.5, glist = NULL, style = 'W', zero.policy = TRUE)
  moran.result<-moran.test(resid(common.ols), nb1.5.w, zero.policy = TRUE)
  moran.result
```

RMF~Aridity index
Also check the SAC from residuals of the regression model.

```{R}
rmfls<-lm(scale(rmf)~scale(Annual_Mean_Temperature)+scale(Tree_Density)+scale(NDVI)+scale(cnratio)+scale(soil_moisture)+scale(Sand_Content_15cm)+scale(Depth_to_Bedrock),data = shrubds) # Linear model is set.
varls<-lm(scale(Aridity_Index)~scale(Annual_Mean_Temperature)+scale(Tree_Density)+scale(NDVI)+scale(cnratio)+scale(soil_moisture)+scale(Sand_Content_15cm)+scale(Depth_to_Bedrock),data = shrubds)
  common.ols<-lm(resid(rmfls)~resid(varls))
  summary(common.ols)
  
  coords<-cbind(shrubds$longitude, shrubds$latitude) # Set coordinates.
  corrds<-as.matrix(coords)
  nb1.5<-dnearneigh(coords,0,4,longlat = TRUE) # Set distance class.
  nb1.5.w<-nb2listw(nb1.5, glist = NULL, style = 'W', zero.policy = TRUE)
  moran.result<-moran.test(resid(common.ols), nb1.5.w, zero.policy = TRUE)
  moran.result
```

RMF~Soil moisture
Also check the SAC from residuals of the regression model.

```{R}
rmfls<-lm(scale(rmf)~scale(Annual_Mean_Temperature)+scale(Tree_Density)+scale(NDVI)+scale(cnratio)+scale(Aridity_Index)+scale(Sand_Content_15cm)+scale(Depth_to_Bedrock),data = shrubds) # Linear model is set.
varls<-lm(scale(soil_moisture)~scale(Annual_Mean_Temperature)+scale(Tree_Density)+scale(NDVI)+scale(cnratio)+scale(Aridity_Index)+scale(Sand_Content_15cm)+scale(Depth_to_Bedrock),data = shrubds)
  common.ols<-lm(resid(rmfls)~resid(varls))
  summary(common.ols)
  
  coords<-cbind(shrubds$longitude, shrubds$latitude) # Set coordinates.
  corrds<-as.matrix(coords)
  nb1.5<-dnearneigh(coords,0,4,longlat = TRUE) # Set distance class.
  nb1.5.w<-nb2listw(nb1.5, glist = NULL, style = 'W', zero.policy = TRUE)
  moran.result<-moran.test(resid(common.ols), nb1.5.w, zero.policy = TRUE)
  moran.result
```

RMF~Soil sand content
Also check the SAC from residuals of the regression model.

```{R}
rmfls<-lm(scale(rmf)~scale(Annual_Mean_Temperature)+scale(Tree_Density)+scale(NDVI)+scale(cnratio)+scale(Aridity_Index)+scale(soil_moisture)+scale(Depth_to_Bedrock),data = shrubds) # Linear model is set.
varls<-lm(scale(Sand_Content_15cm)~scale(Annual_Mean_Temperature)+scale(Tree_Density)+scale(NDVI)+scale(cnratio)+scale(Aridity_Index)+scale(soil_moisture)+scale(Depth_to_Bedrock),data = shrubds)
  common.ols<-lm(resid(rmfls)~resid(varls))
  summary(common.ols)
  
  coords<-cbind(shrubds$longitude, shrubds$latitude) # Set coordinates.
  corrds<-as.matrix(coords)
  nb1.5<-dnearneigh(coords,0,4,longlat = TRUE) # Set distance class.
  nb1.5.w<-nb2listw(nb1.5, glist = NULL, style = 'W', zero.policy = TRUE)
  moran.result<-moran.test(resid(common.ols), nb1.5.w, zero.policy = TRUE)
  moran.result
```


RMF~Soil depth to bedrock
Also check the SAC from residuals of the regression model.

```{R}
rmfls<-lm(scale(rmf)~scale(Annual_Mean_Temperature)+scale(Tree_Density)+scale(NDVI)+scale(cnratio)+scale(Aridity_Index)+scale(soil_moisture)+scale(Sand_Content_15cm),data = shrubds) # Linear model is set.
varls<-lm(scale(Depth_to_Bedrock)~scale(Annual_Mean_Temperature)+scale(Tree_Density)+scale(NDVI)+scale(cnratio)+scale(Aridity_Index)+scale(soil_moisture)+scale(Sand_Content_15cm),data = shrubds)
  common.ols<-lm(resid(rmfls)~resid(varls))
  summary(common.ols)
  
  coords<-cbind(shrubds$longitude, shrubds$latitude) # Set coordinates.
  corrds<-as.matrix(coords)
  nb1.5<-dnearneigh(coords,0,4,longlat = TRUE) # Set distance class.
  nb1.5.w<-nb2listw(nb1.5, glist = NULL, style = 'W', zero.policy = TRUE)
  moran.result<-moran.test(resid(common.ols), nb1.5.w, zero.policy = TRUE)
  moran.result
```


